import {ReactNode} from "react";
import type {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({children}: Readonly<{ children: ReactNode }>) {
	return (
		<div className={"grid grid-cols-[16rem_1fr] flex-1"}>
			<aside className={"h-full max-h-screen border-r border-white/30"}>
				<div className={"max-h-full flex flex-col overflow-scroll"}>
					<NavButton href={"/"}>Overview</NavButton>
					<NavButton href={"menus"}>Menus</NavButton>
				</div>
			</aside>

			<main>
				{children}
			</main>
		</div>
	);
}

function NavButton({href, children}: {
	href: string,
	children?: ReactNode
}) {
	return (<Link href={`/dashboard/${href}`} className={"px-4 py-2 text-2xl hover:bg-white/30 transition"}>{children}</Link>)
}
