import type {Metadata} from "next";
import {Exo_2} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import QueryProvider from "@/app/queryProvider";

const exo = Exo_2({
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="en">
			<body className={`${exo.className} text-body-size antialiased min-h-screen flex flex-col flex-1`}>
				<QueryProvider>
					{children}
				</QueryProvider>
			</body>
		</html>
	);
}
