import type {Metadata} from "next";
import {ReactNode} from "react";
import Header from "@/app/(site)/header";
import Image from "next/image";
import DeviceComponent from "@/components/deviceComponent";
import ContactSection from "@/app/(site)/contactSection";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
	return (
		<div className={"max-h-screen flex flex-col flex-1"}>
			<Header/>

			<DeviceComponent mobile={<MobileLayout/>}>
				<>
					<Image src={"/alien_bg_red.jpg"} alt={"Alien background"} draggable={false} fill preload={true}
						   className={"absolute top-0 left-0 w-full h-full object-cover -z-10"}/>

					<main className={"relative flex-1"}>
						{children}
					</main>

					<ContactSection/>
				</>
			</DeviceComponent>
		</div>
	);

	function MobileLayout() {
		return (
			<div className={"relative flex-1 flex flex-col"}>
				<main className={"flex-1 overflow-scroll relative"}>
					{children}
				</main>
				<ContactSection/>
			</div>
		);
	}
}
